//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mishlen.dataFiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MichelinEntities : DbContext
    {
        public MichelinEntities()
            : base("name=MichelinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientFromOrganization> ClientFromOrganization { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
