//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mishlen.dataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID_Order { get; set; }
        public int id_Product { get; set; }
        public int id_Client { get; set; }
        public int CountOrder { get; set; }
        public int SumOrder { get; set; }
        public System.DateTime DateOrder { get; set; }
    
        public virtual ClientFromOrganization ClientFromOrganization { get; set; }
        public virtual Product Product { get; set; }
    }
}
